// @ts-check

const isDev = process.env.NODE_ENV !== 'production';

/** @type {import('@docusaurus/plugin-content-docs').SidebarItemConfig[]} */
const testCategory = isDev ? [{
  type: 'category',
  label: 'TEST',
  collapsible: true,
  collapsed: false,
  items: [
    { type: 'doc', id: 'cards-test', label: 'Cards Test' },
    { type: 'doc', id: 'admonition-test', label: 'Admonition Test' },
    { type: 'doc', id: 'steps-test', label: 'Steps Test' },
    { type: 'doc', id: 'images-test', label: 'Images Test' },
    { type: 'doc', id: 'demo-image-test', label: 'DemoImage Test' },
    { type: 'doc', id: 'lists-test', label: 'Lists Test' },
    { type: 'doc', id: 'tables-test', label: 'Tables Test' },
  ],
}] : [];

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  ArrowSidebar: [
    // OVERVIEW
    {
      type: 'category',
      label: 'OVERVIEW',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'overview/index' },
      items: [
        { type: 'doc', id: 'overview/about-arrow', label: 'What is Arrow?' },
        { type: 'doc', id: 'overview/our-projects', label: 'Our Projects' },
        { type: 'doc', id: 'designs/bounty-201-power-system', label: 'Power System Design' },
      ],
    },

    // CONTRIBUTING
    {
      type: 'category',
      label: 'CONTRIBUTING',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'contributing/index' },
      items: [
        { type: 'doc', id: 'contributing/intro', label: 'Getting Started' },
        { type: 'doc', id: 'contributing/how-we-work', label: 'How We Work' },
        { type: 'doc', id: 'guides/sign-cla', label: 'Sign the CLA' },
        { type: 'doc', id: 'contributing/grants-bounties', label: 'Grants & Bounties' },
        {
          type: 'category',
          label: 'Meet Our Contributors',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'contributing/contributors/index' },
          customProps: { icon: 'users' },
          items: [{ type: 'autogenerated', dirName: 'contributing/contributors' }],
        },
      ],
    },

    // COMMUNITY
    {
      type: 'category',
      label: 'COMMUNITY',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'community/index' },
      items: [
        { type: 'doc', id: 'community/index', label: 'Community at Arrow' },
        { type: 'doc', id: 'community/contributor-map', label: 'Contributor Map' },
        { type: 'doc', id: 'community/disciplines', label: 'Disciplines' },
        { type: 'doc', id: 'community/community-values', label: 'Culture & Values' },
        { type: 'doc', id: 'community/community-calls', label: 'Calls & Events' },
        { type: 'doc', id: 'community/growth-marketing', label: 'Growth & Marketing' },
      ],
    },

    // GUIDES
    {
      type: 'category',
      label: 'GUIDES',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'guides/index' },
      items: [
        { type: 'doc', id: 'guides/development-guide', label: 'Development Guide' },
        { type: 'doc', id: 'guides/code-of-conduct', label: 'Code of Conduct' },
        { type: 'doc', id: 'contributing/arrow-brand', label: 'Brand Guidelines' },
        { type: 'doc', id: 'community/discord-guide', label: 'Discord Guide' },
      ],
    },

    // DAO
    {
      type: 'category',
      label: 'DAO',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'governance/index' },
      items: [
        { type: 'doc', id: 'governance/why-a-dao', label: 'Why a DAO?' },
        { type: 'doc', id: 'governance/constitution', label: 'Constitution' },
        { type: 'doc', id: 'governance/arrow-token', label: 'ARROW Token' },
        { type: 'doc', id: 'governance/legal-structure', label: 'Legal Structure' },
        { type: 'doc', id: 'governance/core/treasury', label: 'Treasury' },
        {
          type: 'category',
          label: 'AIPs',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'governance/aips/index' },
          items: [{ type: 'autogenerated', dirName: 'governance/aips' }],
        },
        { type: 'doc', id: 'governance/good-to-know/dao-voting', label: 'Voting History' },
        { type: 'doc', id: 'governance/good-to-know/submit-proposal', label: 'Submitting a Proposal' },
        { type: 'doc', id: 'changelog', label: 'Changelog' },
      ],
    },

    // TEST PAGES — dev-only. Built above as `testCategory`. Each *-test.mdx
    // also has `draft: true` front matter so the pages themselves don't ship.
    ...testCategory,

    // RESOURCES
    {
      type: 'category',
      label: 'RESOURCES',
      collapsible: true,
      collapsed: false,
      items: [
        { type: 'doc', id: 'reference/dao-forum', label: 'DAO Forum' },
        { type: 'doc', id: 'reference/snapshot', label: 'Snapshot' },
        { type: 'doc', id: 'reference/contracts/index', label: 'Token Contracts' },
        { type: 'link', label: 'Google Drive', href: 'https://drive.google.com' },
        { type: 'doc', id: 'reference/discord', label: 'Discord Server' },
        { type: 'link', label: 'Twitter', href: 'https://twitter.com' },
      ],
    },
  ],
};

module.exports = sidebars;
