// @ts-check

const isDev = process.env.NODE_ENV !== 'production';

/** @type {import('@docusaurus/plugin-content-docs').SidebarItemConfig[]} */
const testCategory = isDev ? [{
  type: 'category',
  label: 'TEST',
  collapsible: true,
  collapsed: false,
  items: [
    { type: 'doc', id: 'cards-test', label: 'Cards Test' },
    { type: 'doc', id: 'admonition-test', label: 'Admonition Test' },
    { type: 'doc', id: 'steps-test', label: 'Steps Test' },
    { type: 'doc', id: 'images-test', label: 'Images Test' },
    { type: 'doc', id: 'demo-image-test', label: 'DemoImage Test' },
    { type: 'doc', id: 'lists-test', label: 'Lists Test' },
    { type: 'doc', id: 'tables-test', label: 'Tables Test' },
  ],
}] : [];

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  ArrowSidebar: [
    // OVERVIEW
    {
      type: 'category',
      label: 'OVERVIEW',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'overview/index' },
      items: [
        { type: 'doc', id: 'overview/about-arrow', label: 'What is Arrow?' },
        { type: 'doc', id: 'overview/getting-started', label: 'Getting Started' },
        { type: 'doc', id: 'overview/our-projects', label: 'Our Projects' },
      ],
    },

    // CONTRIBUTING
    {
      type: 'category',
      label: 'CONTRIBUTING',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'contributing/index' },
      items: [
        { type: 'doc', id: 'contributing/intro', label: 'Start Contributing' },
        { type: 'doc', id: 'guides/sign-cla', label: 'Sign the CLA' },
        { type: 'doc', id: 'contributing/grants-bounties', label: 'Grants & Bounties' },
        {
          type: 'category',
          label: 'Guides',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'guides/index' },
          items: [
            { type: 'doc', id: 'guides/development-guide', label: 'Development Guide' },
            { type: 'doc', id: 'guides/github-guide', label: 'GitHub Guide' },
            { type: 'doc', id: 'community/discord-guide', label: 'Discord Guide' },
            { type: 'doc', id: 'contributing/arrow-brand', label: 'Brand Guidelines' },
          ],
        },
        {
          type: 'category',
          label: 'Meet Our Contributors',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'contributing/contributors/index' },
          customProps: { icon: 'users' },
          items: [{ type: 'autogenerated', dirName: 'contributing/contributors' }],
        },
      ],
    },

    // COMMUNITY
    {
      type: 'category',
      label: 'COMMUNITY',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'community/index' },
      items: [
        { type: 'doc', id: 'community/index', label: 'Community at Arrow' },
        {
          type: 'category',
          label: 'How We Work',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'contributing/how-we-work' },
          items: [
            { type: 'doc', id: 'community/community-values', label: 'Culture & Values' },
            { type: 'doc', id: 'community/working-async', label: 'Working Async' },
            { type: 'doc', id: 'guides/code-of-conduct', label: 'Code of Conduct' },
          ],
        },
        { type: 'doc', id: 'community/community-calls', label: 'Calls & Events' },
        {
          type: 'category',
          label: 'People',
          collapsible: true,
          collapsed: true,
          items: [
            { type: 'doc', id: 'community/contributor-map', label: 'Contributor Map' },
            { type: 'doc', id: 'community/disciplines', label: 'Disciplines' },
          ],
        },
        { type: 'doc', id: 'community/growth-marketing', label: 'Growth & Marketing' },
      ],
    },

    // DAO
    {
      type: 'category',
      label: 'DAO',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'governance/index' },
      items: [
        { type: 'doc', id: 'governance/why-a-dao', label: 'Why a DAO?' },
        {
          type: 'category',
          label: 'Foundations',
          collapsible: true,
          collapsed: true,
          items: [
            { type: 'doc', id: 'governance/constitution', label: 'Constitution' },
            { type: 'doc', id: 'governance/legal-structure', label: 'Legal Structure' },
            { type: 'doc', id: 'governance/arrow-token', label: 'ARROW Token' },
          ],
        },
        {
          type: 'category',
          label: 'Funding',
          collapsible: true,
          collapsed: true,
          items: [
            { type: 'doc', id: 'governance/core/treasury', label: 'Treasury' },
            { type: 'doc', id: 'governance/active-project-list', label: 'Active Projects' },
            { type: 'doc', id: 'governance/gbc', label: 'Grants & Bounties Committee' },
          ],
        },
        {
          type: 'category',
          label: 'Proposals & Voting',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'AIPs',
              collapsible: true,
              collapsed: true,
              link: { type: 'doc', id: 'governance/aips/index' },
              items: [{ type: 'autogenerated', dirName: 'governance/aips' }],
            },
            { type: 'doc', id: 'governance/good-to-know/submit-proposal', label: 'Submitting a Proposal' },
            { type: 'doc', id: 'governance/good-to-know/dao-voting', label: 'Voting History' },
          ],
        },
      ],
    },

    // TEST PAGES — dev-only. Built above as `testCategory`. Each *-test.mdx
    // also has `draft: true` front matter so the pages themselves don't ship.
    ...testCategory,

    // RESOURCES
    {
      type: 'category',
      label: 'RESOURCES',
      collapsible: true,
      collapsed: false,
      items: [
        { type: 'link', label: 'DAO Forum', href: 'https://dao.arrowair.com/' },
        { type: 'doc', id: 'reference/snapshot', label: 'Snapshot' },
        { type: 'doc', id: 'reference/glossary', label: 'Glossary' },
        {
          type: 'category',
          label: 'Token Contracts',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'reference/contracts/index' },
          items: [
            { type: 'doc', id: 'reference/contracts/api/index', label: 'API Reference' },
            { type: 'doc', id: 'reference/contracts/guides/vesting', label: 'Vesting' },
          ],
        },
        { type: 'doc', id: 'changelog', label: 'Changelog' },
        { type: 'link', label: 'Discord', href: 'https://discord.com/invite/arrow' },
        { type: 'link', label: 'X', href: 'https://x.com/ArrowAir_' },
      ],
    },
  ],
};

module.exports = sidebars;
