name: Build and deploy docs from S3 to S3

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        description: "The node version to use for node setup"
      environment:
        required: true
        type: string
        description: "Environment to deploy to"
    outputs:
      files_changed:
        description: "Amount of files uploaded to / deleted from S3 during sync"
        value: "${{ jobs.build.outputs.files_changed }}"

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Set up node ${{ inputs.node-version }}
       uses: actions/setup-node@v2
       with:
         node-version: ${{ inputs.node-version }}
         cache: yarn
     - name: Install dependencies
       run: yarn install --frozen-lockfile
 #   - name: Run Lint
 #     run: yarn lint
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         role-to-assume: "${{ secrets.AWS_ROLE_ARN }}"
         role-session-name: arrow-website-pull-docs
         aws-region: "us-east-2"
     - name: Sync files from S3 for processing
       run: |
         aws s3 sync "s3://${{ github.event.client_payload.aws_s3_source_bucket }}${{ github.event.client_payload.docs_path }}" "./${{ github.event.client_payload.docs_path }}"
     - name: Build
       run: yarn build
     - name: Deploy to ${{ inputs.environment }} S3
       id: sync_s3
       run: |
         FILES_CHANGED=$(aws s3 sync "./build/${{ github.event.client_payload.docs_path }}" "s3://${{ secrets.AWS_S3_BUCKET }}${{ github.event.client_payload.docs_path }}" --delete --size-only | wc -l)
         echo "::set-output name=files_changed::$FILES_CHANGED"
    outputs:
      files_changed: "${{ steps.build-and-deploy.outputs.files_changed }}"
