name: Deploy Staging

on:
  schedule:
    - cron: '0 4 * * *' # run at 4 AM UTC
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      node-version: 19.x
      environment: staging
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  invalidate-cloudfront:
    uses: ./.github/workflows/invalidate-cloudfront.yml
    needs: [build-and-deploy]
    with:
      paths: "/*"
      environment: staging
    secrets: inherit
    permissions:
      id-token: write
      contents: read
