name: Deploy Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      node-version: 14.x
      environment: staging
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  invalidate-cloudfront:
    uses: ./.github/workflows/invalidate-cloudfront.yml
    needs: [build-and-deploy]
    with:
      paths: "/*"
      environment: staging
    secrets: inherit
    permissions:
      id-token: write
      contents: read
