name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  production:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      node-version: 14.x
      environment: production
    secrets: inherit
    permissions:
      id-token: write
      contents: read
