name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      node-version: 14.x
      environment: main
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  invalidate-cloudfront:
    uses: ./.github/workflows/invalidate-cloudfront.yml
    needs: [build-and-deploy]
    with:
      paths: "/*"
      environment: main
    secrets: inherit
    permissions:
      id-token: write
      contents: read
