name: Deploy generated docs

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-docs]

jobs:
  build-and-deploy-docs:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      node-version: 14.x
      environment: ${{ github.event.client_payload.environment }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  invalidate-cloudfront:
    uses: ./.github/workflows/invalidate-cloudfront.yml
    needs: [build-and-deploy-docs]
    with:
      paths: "/*"
      environment: ${{ github.event.client_payload.environment }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
