name: Sanity checks

env:
  TERM: xterm

on:
  push:
    branches:
      - staging
      - main
  pull_request:

jobs:
  spellcheck: # run the action
    name: CSpell Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make cspell-test

  link-test: # run the action
    name: Broken Link Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make link-test